"""Generate the daily_challenges block for schedule.yaml from the course 833 backup.

Cogniterra course 833 still carries Fall 2025 dates. Fall 2025 and Fall 2026 are offset by
exactly 364 days (52 weeks), so every challenge keeps its weekday and both structural gaps
(fall break, Thanksgiving) land correctly. This script records that mapping; it writes
nothing back to Cogniterra.

Usage:  python3 import_daily_challenges.py > daily_challenges.yaml
"""

import datetime
import json
import re
from pathlib import Path

BACKUP = Path(
    "/Users/phillipcompeau/Library/CloudStorage/GoogleDrive-pcompeau@andrew.cmu.edu/"
    "My Drive/Courses/2026/Fall/02-120/Daily Challenges/backup_2026-08-08/"
    "course833_full_backup.json"
)
SHIFT = datetime.timedelta(days=364)


def classify(title: str) -> str:
    """Label a challenge by what it asks of the student."""
    lowered = title.lower()
    if "exam!" in lowered:
        return "exam"
    if "study!" in lowered:
        return "study"
    if "reading!" in lowered:
        return "reading"
    if title.startswith("Weekend"):
        return "weekend"
    return "challenge"


def load_lessons() -> list[dict[str, object]]:
    """Read the backup and return one dated record per lesson, sorted by F26 date."""
    data = json.loads(BACKUP.read_text())
    raw = data["lessons"]
    if not isinstance(raw, list):
        raw = list(raw.values())
    records: list[dict[str, object]] = []
    for lesson in raw:
        title = lesson.get("title", "")
        found = re.search(r"(\d{1,2})/(\d{1,2})", title)
        if found is None:
            continue
        old = datetime.date(2025, int(found.group(1)), int(found.group(2)))
        record = {
            "date": old + SHIFT,
            "was": old,
            "lesson": lesson.get("id"),
            "kind": classify(title),
            "title": title,
        }
        records.append(record)
    records.sort(key=lambda item: item["date"])
    return records


def main() -> None:
    """Print the YAML block."""
    records = load_lessons()
    print("# Generated by import_daily_challenges.py. Do not hand-edit dates here;")
    print("# regenerate after course 833 is re-dated to Fall 2026.")
    print("daily_challenges:")
    for record in records:
        print(f"  - date: {record['date'].isoformat()}")
        print(f"    lesson: {record['lesson']}")
        print(f"    kind: {record['kind']}")
        print(f"    was: {record['was'].isoformat()}   # title on Cogniterra still says this")
    print(f"# {len(records)} challenges mapped")


main()
